# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
