# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_auto_20171111_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePredictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.CharField(max_length=12)),
                ('prediction', models.CharField(max_length=32)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
